export const planetInfo = {
  planet1: {
    name: '',
    overview: '',
    source: '',
    internalStruct: '',
    surfaceGeo: '',
    rotation: '',
    revolution: '',
    radius: '',
    avgTemp: '',
    keyColor: '',
  },
  planet2: {
    name: '',
    overview: '',
    source: '',
    internalStruct: '',
    surfaceGeo: '',
    rotation: '',
    revolution: '',
    radius: '',
    avgTemp: '',
    keyColor: '',
  },
  planet3: {
    name: '',
    overview: '',
    source: '',
    internalStruct: '',
    surfaceGeo: '',
    rotation: '',
    revolution: '',
    radius: '',
    avgTemp: '',
    keyColor: '',
  },
  planet4: {
    name: '',
    overview: '',
    source: '',
    internalStruct: '',
    surfaceGeo: '',
    rotation: '',
    revolution: '',
    radius: '',
    avgTemp: '',
    keyColor: '',
  },
  planet5: {
    name: '',
    overview: '',
    source: '',
    internalStruct: '',
    surfaceGeo: '',
    rotation: '',
    revolution: '',
    radius: '',
    avgTemp: '',
    keyColor: '',
  },
  planet6: {
    name: '',
    overview: '',
    source: '',
    internalStruct: '',
    surfaceGeo: '',
    rotation: '',
    revolution: '',
    radius: '',
    avgTemp: '',
    keyColor: '',
  },
  planet7: {
    name: '',
    overview: '',
    source: '',
    internalStruct: '',
    surfaceGeo: '',
    rotation: '',
    revolution: '',
    radius: '',
    avgTemp: '',
    keyColor: '',
  },
  planet8: {
    name: '',
    overview: '',
    source: '',
    internalStruct: '',
    surfaceGeo: '',
    rotation: '',
    revolution: '',
    radius: '',
    avgTemp: '',
    keyColor: '',
  },
};
